// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user": {
            "post": {
                "description": "Create a new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create a new user.",
                "parameters": [
                    {
                        "description": "Create User Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{username}/balance": {
            "get": {
                "description": "Get balances of user's wallets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get balances of user's wallets.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserWalletBalanceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{username}/transactions": {
            "get": {
                "description": "Get transactions of user's wallets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get transactions of user's wallets.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserTransactionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallet": {
            "post": {
                "description": "Create a new wallet for user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Create a new wallet for user.",
                "parameters": [
                    {
                        "description": "Create Wallet Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateWalletRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CreateWalletResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cryptonlx_crypto_src_controller_mux_user.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "github_com_cryptonlx_crypto_src_controller_mux_user.Wallet": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "user_account_id": {
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "type": "string",
                    "example": "10.000123"
                }
            }
        },
        "user.CreateUserRequestBody": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.CreateUserResponseData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserResponseData": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/user.CreatedUser"
                }
            }
        },
        "user.CreateWalletRequestBody": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.CreateWalletResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.CreateWalletResponseData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "user.CreateWalletResponseData": {
            "type": "object",
            "properties": {
                "wallet": {
                    "$ref": "#/definitions/user.CreatedWallet"
                }
            }
        },
        "user.CreatedUser": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "user.CreatedWallet": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "user_account_id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "user.ErrorResponse": {
            "type": "object"
        },
        "user.GetUserTransactionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.GetUserTransactionsResponseData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "user.GetUserTransactionsResponseData": {
            "type": "object"
        },
        "user.GetUserWalletBalanceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.GetWalletBalanceResponseData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "user.GetWalletBalanceResponseData": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github_com_cryptonlx_crypto_src_controller_mux_user.User"
                },
                "wallets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cryptonlx_crypto_src_controller_mux_user.Wallet"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Cryptocom",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
