definitions:
  user.ErrorResponse:
    type: object
  user.GetUserBalanceResponseData:
    type: object
  user.GetUserWalletBalanceResponse:
    properties:
      data:
        $ref: '#/definitions/user.GetUserBalanceResponseData'
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/{user_id}/balance:
    get:
      consumes:
      - application/json
      description: Get balances of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetUserWalletBalanceResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Get balances of user's wallets.
      tags:
      - user
swagger: "2.0"
