definitions:
  github_com_cryptonlx_crypto_src_controllers_mux_user.Ledger:
    properties:
      amount:
        example: "40.22"
        type: string
      balance:
        example: "2.234"
        type: string
      created_at:
        type: string
      entry_type:
        description: Operation string    `json:"operation" example:"deposit,withdraw,transfer"`
        example: credit,debit
        type: string
      id:
        example: 1
        type: integer
      transaction_id:
        example: 1749286345000
        type: integer
      wallet_id:
        example: 1
        type: integer
    type: object
  github_com_cryptonlx_crypto_src_controllers_mux_user.Transaction:
    properties:
      created_at:
        type: string
      id:
        example: 1
        type: integer
      ledgers:
        items:
          $ref: '#/definitions/github_com_cryptonlx_crypto_src_controllers_mux_user.Ledger'
        type: array
      nonce:
        type: integer
      operation:
        type: string
      status:
        type: string
      user_account_id:
        example: 1
        type: integer
    type: object
  github_com_cryptonlx_crypto_src_controllers_mux_user.User:
    properties:
      id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  github_com_cryptonlx_crypto_src_controllers_mux_user.Wallet:
    properties:
      balance:
        example: "10.000123"
        type: string
      currency:
        example: USD
        type: string
      id:
        example: 1
        type: integer
      user_account_id:
        example: 1
        type: integer
    type: object
  user.CreateUserRequestBody:
    properties:
      username:
        type: string
    type: object
  user.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/user.CreateUserResponseData'
      error:
        type: string
    type: object
  user.CreateUserResponseData:
    properties:
      user:
        $ref: '#/definitions/user.CreatedUser'
    type: object
  user.CreateWalletRequestBody:
    properties:
      currency:
        type: string
      username:
        type: string
    type: object
  user.CreateWalletResponseBody:
    properties:
      data:
        $ref: '#/definitions/user.CreateWalletResponseData'
      error:
        type: string
    type: object
  user.CreateWalletResponseData:
    properties:
      wallet:
        $ref: '#/definitions/user.CreatedWallet'
    type: object
  user.CreatedUser:
    properties:
      id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  user.CreatedWallet:
    properties:
      balance:
        example: user1
        type: string
      currency:
        example: USD
        type: string
      id:
        example: 1
        type: integer
      user_account_id:
        example: 1
        type: integer
    type: object
  user.DepositRequestBody:
    properties:
      amount:
        example: "10.23"
        type: string
      nonce:
        example: 1749286345000
        type: integer
    type: object
  user.DepositResponseBody:
    properties:
      data:
        $ref: '#/definitions/user.DepositResponseData'
      error:
        type: string
    type: object
  user.DepositResponseData:
    properties:
      transaction:
        $ref: '#/definitions/github_com_cryptonlx_crypto_src_controllers_mux_user.Transaction'
    type: object
  user.ErrorResponseBody:
    type: object
  user.GetWalletsResponseBody:
    properties:
      data:
        $ref: '#/definitions/user.GetWalletsResponseData'
      error:
        type: string
    type: object
  user.GetWalletsResponseData:
    properties:
      user:
        $ref: '#/definitions/github_com_cryptonlx_crypto_src_controllers_mux_user.User'
      wallets:
        items:
          $ref: '#/definitions/github_com_cryptonlx_crypto_src_controllers_mux_user.Wallet'
        type: array
    type: object
  user.TransactionsResponseBody:
    properties:
      data:
        $ref: '#/definitions/user.TransactionsResponseData'
      error:
        type: string
    type: object
  user.TransactionsResponseData:
    properties:
      transactions:
        items:
          $ref: '#/definitions/github_com_cryptonlx_crypto_src_controllers_mux_user.Transaction'
        type: array
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user.
      parameters:
      - description: Create User Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponseBody'
      summary: Create a new user.
      tags:
      - user
  /user/{username}/transactions:
    get:
      consumes:
      - application/json
      description: Get transactions of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.TransactionsResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponseBody'
      summary: Get transactions of user's wallets.
      tags:
      - wallet
  /user/{username}/wallets:
    get:
      consumes:
      - application/json
      description: Get balances of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetWalletsResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponseBody'
      summary: Get balances of user's wallets.
      tags:
      - wallet
  /wallet:
    post:
      consumes:
      - application/json
      description: Create a new wallet for user.
      parameters:
      - description: Create Wallet Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateWalletRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateWalletResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponseBody'
      summary: Create a new wallet for user.
      tags:
      - wallet
  /wallet/{wallet_id}/deposit:
    post:
      consumes:
      - application/json
      description: Deposit to wallet
      parameters:
      - description: wallet id
        in: path
        name: wallet_id
        required: true
        type: string
      - description: Create Deposit Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.DepositRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.DepositResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponseBody'
      security:
      - BasicAuth: []
      summary: Deposit to wallet
      tags:
      - wallet
swagger: "2.0"
