definitions:
  github_com_cryptonlx_crypto_src_controller_mux_user.User:
    properties:
      id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  user.CreateRequestBody:
    properties:
      username:
        description: Subreddit Name
        type: string
    type: object
  user.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/github_com_cryptonlx_crypto_src_controller_mux_user.User'
      error:
        type: string
    type: object
  user.ErrorResponse:
    type: object
  user.GetUserBalanceResponseData:
    type: object
  user.GetUserWalletBalanceResponse:
    properties:
      data:
        $ref: '#/definitions/user.GetUserBalanceResponseData'
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user.
      parameters:
      - description: Create Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Create a new user.
      tags:
      - user
  /user/{username}/balance:
    get:
      consumes:
      - application/json
      description: Get balances of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetUserWalletBalanceResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Get balances of user's wallets.
      tags:
      - wallet
swagger: "2.0"
