definitions:
  github_com_cryptonlx_crypto_src_controller_mux_user.User:
    properties:
      id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  github_com_cryptonlx_crypto_src_controller_mux_user.Wallet:
    properties:
      currency:
        example: USD
        type: string
      id:
        example: 1
        type: integer
      user_account_id:
        example: 1
        type: integer
      value:
        example: "10.000123"
        type: string
    type: object
  user.CreateUserRequestBody:
    properties:
      username:
        type: string
    type: object
  user.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/user.CreateUserResponseData'
      error:
        type: string
    type: object
  user.CreateUserResponseData:
    properties:
      user:
        $ref: '#/definitions/user.CreatedUser'
    type: object
  user.CreateWalletRequestBody:
    properties:
      currency:
        type: string
      username:
        type: string
    type: object
  user.CreateWalletResponse:
    properties:
      data:
        $ref: '#/definitions/user.CreateWalletResponseData'
      error:
        type: string
    type: object
  user.CreateWalletResponseData:
    properties:
      wallet:
        $ref: '#/definitions/user.CreatedWallet'
    type: object
  user.CreatedUser:
    properties:
      id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  user.CreatedWallet:
    properties:
      currency:
        example: USD
        type: string
      id:
        example: 1
        type: integer
      user_account_id:
        example: 1
        type: integer
      username:
        example: user1
        type: string
    type: object
  user.ErrorResponse:
    type: object
  user.GetUserTransactionsResponse:
    properties:
      data:
        $ref: '#/definitions/user.GetUserTransactionsResponseData'
      error:
        type: string
    type: object
  user.GetUserTransactionsResponseData:
    type: object
  user.GetUserWalletBalanceResponse:
    properties:
      data:
        $ref: '#/definitions/user.GetWalletBalanceResponseData'
      error:
        type: string
    type: object
  user.GetWalletBalanceResponseData:
    properties:
      user:
        $ref: '#/definitions/github_com_cryptonlx_crypto_src_controller_mux_user.User'
      wallets:
        items:
          $ref: '#/definitions/github_com_cryptonlx_crypto_src_controller_mux_user.Wallet'
        type: array
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user.
      parameters:
      - description: Create User Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Create a new user.
      tags:
      - user
  /user/{username}/balance:
    get:
      consumes:
      - application/json
      description: Get balances of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetUserWalletBalanceResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Get balances of user's wallets.
      tags:
      - wallet
  /user/{username}/transactions:
    get:
      consumes:
      - application/json
      description: Get transactions of user's wallets.
      parameters:
      - description: username
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetUserTransactionsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Get transactions of user's wallets.
      tags:
      - wallet
  /wallet:
    post:
      consumes:
      - application/json
      description: Create a new wallet for user.
      parameters:
      - description: Create Wallet Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateWalletRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateWalletResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.ErrorResponse'
      summary: Create a new wallet for user.
      tags:
      - wallet
swagger: "2.0"
